title: Progrm의 블로그
description: 여러가지 잡다한 것을 하는 사람의 공간.
social_link: twitter
social_username: broccolini
github_repo: progrm-github
github_username: progrm-github
theme_color: black
remote_theme: internet-de-france/swiss
baseurl: /progrm
defaults:
  - scope:
      path: ''
      type: pages
    values:
      category_name: ''
  - scope:
      path: ''
      type: posts
    values:
      categories: ''
remote_theme_layouts:
  - ''
  - default
  - page
  - post
  - home
  - category_index
social_links:
  - twitter
  - instagram
  - medium
  - dribbble
theme_colors:
  - black
  - blue
  - gray
  - magenta
  - orange
  - red
  - white
  - yellow
